// MExNPrototypes/MEANclient/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './components/header/header.component';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, HeaderComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'client';
}

<h1>Nelson Disaster Response Angular Prototype</h1>
<app-header></app-header>
<router-outlet></router-outlet>

// MilestoneThreeWebsite/MEVNclient/src/App.vue
<template>
  <div id="app">
    <h1>Nelson Disaster Response Vue Prototype</h1>
    <HeaderComponent />
    <router-view />
  </div>
</template>

<script>
import HeaderComponent from './components/Header.vue'

export default {
  name: 'App',
  components: {
    HeaderComponent
  }
}
</script>

<style>
/* global styles */
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  margin: 0;
  padding: 0;
}
</style>
